services:
  - type: web
    name: arruma-aqui
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn arruma.wsgi:application"  # ← Mude aqui
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arruma-aqui-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: arruma.settings  # ← Mude aqui

databases:
  - name: arruma-aqui-db
    plan: free
