sservices:
  - type: web
    name: arruma-aqui
    env: python
    plan: free
    pythonVersion: "3.11.9"  # ← FORÇA a versão aqui
    buildCommand: "./build.sh"
    startCommand: "gunicorn arruma.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arruma-aqui-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: arruma-aqui-db
    plan: free
